name: MatthewFieger
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

url: "http://matthewfieger.com/" # for production
# url: "http://0.0.0.0:4000/" # for staging

exclude: ["CNAME", "README.md"] # exclude files from site build

paginate: 25 # maximum number of posts you’d like to be displayed per page
paginate_path: "blog/page:num" # specify where the destination of the pagination pages
